<?php

/**
 * @file
 * Provides a generic CRM party entity.
 */

include_once("includes/crm_party.entity.inc");
include_once("includes/crm_party_type.entity.inc");

/**
 * Implements hook_entity_info().
 *
 * Define 2 entities here - the actual entity that will hold our domain 
 * specific information and an entity that holds information about the 
 * different types of entities.
 */
function crm_party_entity_info() {
  $party_info['crm_party'] = array(
    'label' => t('Party'),
    'entity class' => 'CRMParty',
    'controller class' => 'CRMPartyController',
    'base table' => 'crm_party',
    //'uri callback' => 'crm_party_uri',
    'fieldable' => TRUE,
    'module' => 'crm_party',
    'entity keys' => array(
      'id' => 'pid',
      'bundle' => 'type',
    ),
    'exportable' => TRUE,
    //'static cache' => TRUE,
    'bundles' => array(
      'individual' => array(
        'label' => t('Individual Party'),
        'admin' => array(
          'path' => 'admin/community/party/manage/individual',
          'access arguments' => array('administer parties'),
        ),
      ),
      'organisation' => array(
        'label' => t('Organisation Party'),
        'admin' => array(
          'path' => 'admin/community/party/manage/organisation',
          'access arguments' => array('administer parties'),
        ),
      ),
    ),
    'bundle keys' => array(
      'bundle' => 'type',
    ),
    'view modes' => array(
      'full' => array(
        'label' => t('Full Contact'),
        'custom settings' =>  FALSE,
      ),
    )
  );
  
  return $party_info;
}

/**
 * Implements hook_entity_info_alter().
 *
 * We are adding the info about the model types via a hook to avoid a recursion
 * issue as loading the model types requires the entity info as well.
 *
 * @todo This needs to be improved
 *
function crm_party_entity_info_alter(&$entity_info) {
  foreach (crm_party_get_types() as $type => $info) {
    $entity_info['crm_party']['bundles'][$type] = array(
      'label' => $info->label,
      'admin' => array(
        'path' => 'admin/community/structure/party_types/manage/%crm_party_type',
        'real path' => 'admin/community/structure/party_types/manage/' . $type,
        'bundle argument' => 4,
        'access arguments' => array('administer party types'),
      ),
    );
  }
}
*/

/**
 * Implements hook_menu().
 */
function crm_party_menu() {
  $items['admin/community'] = array(
    'title' => 'Community',
    'description' => 'Manage the community',
    'page callback' => 'crm_party_admin',
    'page arguments' => array('list'),
    'access arguments' => array('administer parties'),
    'position' => 'left',
    'file' => 'crm_party.admin.inc',  
  );
  $items['admin/community/party/manage'] = array(
    'title' => 'Party Admin',
    'description' => 'Manage Contact Information',
    'page callback' => 'crm_party_info',
    'access arguments' => array('administer parties'),
  );
  $items['admin/community/party/manage/individual'] = array(
    'title' => 'Manage Individuals',
    'description' => 'Manage Contact Information',
    'page callback' => 'crm_party_manage',
    'page arguments' => array('individual'),
    'access arguments' => array('administer parties'),
  );
  $items['admin/community/party/manage/organisation'] = array(
    'title' => 'Manage Organisations',
    'description' => 'Manage Contact Information',
    'page callback' => 'crm_party_manage',
    'page arguments' => array('organisation'),
    'access arguments' => array('administer parties'),
  );
  $items['party/%crm_party'] = array(
    'title callback' => 'crm_party_page_title',
    'title arguments' => array(1),
    'page callback' => 'crm_party_page_view',
    'page arguments' => array(1),
    'access arguments' => array('view contacts'),
    'type' => MENU_CALLBACK,
  );
  $items['party/%crm_party/edit'] = array(
    'title callback' => 'crm_party_edit_page_title',
    'title arguments' => array(1),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('crm_party_edit_form', 1),
    'access arguments' => array('edit contacts'),
    'type' => MENU_CALLBACK,
  );
  
  $items['party/add'] = array(
    'title' => 'Add Party',
    'page callback' => 'crm_party_add',
    'access arguments' => array('create contacts'),
  );
  $items['party/add/individual'] = array(
    'title' => 'Add Individual',
    'page callback' => 'crm_party_add',
    'page arguments' => array('individual'),
    'access arguments' => array('create contacts'),
  );
  $items['party/add/organisation'] = array(
    'title' => 'Add Organisation',
    'page callback' => 'crm_party_add',
    'page arguments' => array('organisation'),
    'access arguments' => array('create contacts'),
  );
  
  return $items;
}

/**
 * Implements hook_permission().
 */
function crm_party_permission() {
    return array(
    'administer party types' => array(
      'title' => t('Administer Party Types'),
      'restrict access' => TRUE,
    ),
    'administer parties' =>  array(
      'title' => t('Administer Parties'),
      'restrict access' => TRUE,
    ),
    'create parties' => array(
      'title' => t('Create Parties'),
    ),
    'view parties' => array(
      'title' => t('View Parties'),
    ),
    'edit parties' => array(
      'title' => t('Edit Parties'),
    )
  );
}

/**
 * URI callback for contacts.
 */
function crm_party_uri($party) {
  return array('path' => 'party/' . $party->pid, );
}

/**
 * Implements hook_theme().
 */
function crm_party_theme() {
  return array(
    'crm_party_email' => array(
      'variables' => array('crm_party_email', 'crm_party' => NULL),
      'template' => 'crm_party_email',
    ),
  );
}

/**
 * Load a single contact.
 */
function crm_party_load($pid = NULL, $reset = FALSE) {
  $pids = (isset ($pid) ? array($pid) : array());
  $party = crm_party_load_multiple($pids, $reset);
  return $party ? reset ($party) : FALSE;
}

/**
 * Load many contacts.
 */ 
function crm_party_load_multiple($pids = array(), $conditions = array(), $reset = FALSE) {
  return entity_load('crm_party', $pids, $conditions, $reset);
}

/**
 * pages - to be moved to a different file
 */
/**
 * Mock up the CRM Party admin interface - this is horrible: do it a better way.
 */
function crm_party_info() {
  // @todo: load bundles from entity info.
  // @todo: probably some of this admin UI can be done by EntityAPI.
  $types = array(
    'individual' => array(
      'label' => t('Individual Party'),
      'description' => 'Parties representing individual people',
      'admin' => array(
        'path' => 'admin/community/party/manage/individual',
        'access arguments' => array('administer parties'),
      ),
    ),
    'organisation' => array(
      'label' => t('Organisation Party'),
      'description' => 'Parties representing organisations or groups of people',
      'admin' => array(
        'path' => 'admin/community/party/manage/organisation',
        'access arguments' => array('administer parties'),
      ),
    ),
  );
  
  $rows = array();
  
  foreach($types as $type => $info) {
    $rows[] = array(
      $info['label'] . " <small>(Machine name: ".$type.")</small><div class=\"description\">".$info['description']."</div>",
      array(
        'data' => l(t('edit'), 'admin/community/party/manage/'.$type),
      ),
      array(
        'data' => l(t('Manage Fields'), 'admin/community/party/manage/'.$type.'/fields'),
      ),
      array(
        'data' => l(t('Manage Fields'), 'admin/community/party/manage/'.$type.'/display'),
      ),
      array(
        'data' => '', //for when we implement custom party types
      ),
    );
  }
  
  
  return array(
    'party_table' => array(
      '#theme' => 'table',
      '#header' => array(
        t('Party Type'), array('data' => t('Operations'), 'colspan' => '4'),
      ),
      '#rows' => $rows,
    ),
  );
}

/**
 * The management page for each party type.
 */
function crm_party_manage($type) {
  return "Welcome to the party type administration page for " . $type;
}

function crm_party_page_title($party) {
  return $party->label;
}

function crm_party_page_view($party, $view_mode = 'full') {
  $party->content = array();
  
  $controller = entity_get_controller('crm_party');  
  $content = $controller->view(array($party->pid => $party));
  drupal_set_title($party->label);
  return $content;  
  
}

function crm_party_edit_page_title($party) {
  return "Edit " . $party->label;
} 

/**
 * Add Contact Page
 */
function crm_party_add($type = '') {
  if ($type == '') {
    // @todo: use theme_item_list().
    return "<ul class=\"admin-list\">
              <li class=\"leaf\">".l(t('Add Individual'), 'party/add/individual')."<div class=\"description\">Add an individual party</div></li>
              <li class=\"leaf\">".l(t('Add Organisation'), 'party/add/organisation')."Add Organisation</a><div class=\"description\">Add an organisation party</div></li>
            </ul>";
  }
  
  $party = (object) array(
    'type' => $type,
    'label' => '',
  );
    
  return drupal_get_form('crm_party_edit_form', $party);
}

function crm_party_edit_form($form, &$form_state, $party) {
  if(isset($party->pid)) {
    $form['pid'] = array(
      '#type' => 'value',
      '#value' => $party->pid,
    );
  }
  
  $form['type'] = array(
    '#type' => 'hidden',
    '#value' => $party->type,
  );
  
  $form['label'] = array(
    '#type' => 'textfield',
    '#title' => t('Party Label'),
    '#required' => TRUE,
    '#default_value' => $party->label,
  );
  
  field_attach_form('crm_party', $party, $form, $form_state);
  
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
    '#weight' => 99,
  );

  return $form;
}

function crm_party_edit_form_validate($form, &$form_state) {
  $submission = (object) $form_state['values'];
  field_attach_form_validate('crm_party', $submission, $form, $form_state);  
}

function crm_party_edit_form_submit($form, &$form_state) {
  $party = (object) $form_state['values'];
  field_attach_submit('crm_party', $party, $form, $form_state);
  $party = crm_party_save($party);
  $form_state['crm_party'] = $party;
  $form_state['redirect'] = 'party/' . $party->pid;
}

/**
 * Delete a party.
 */
function crm_party_delete(CRMParty $party) {
  $party->delete();
}

/**
 * Save a crm_party.
 *
 *  @param $info
 *
 */
function crm_party_save(&$party) {
  return entity_get_controller('crm_party')->save($party);
}

/**
 * Create a crm_party array ready for saving to the database.
 *
 *  @param $info
 *    An array carrying all the important information.
 */
function crm_party_create($info) {
  if (!is_array($info)) {
    return FALSE;
  }
  if (!isset($info['type'])) {
    return FALSE;
  }
  if (!isset($info['label'])) {
    return FALSE;
  }
  
  return (object) $info;  
}

/**
 * Implements hook_party_operations.
 */
function crm_party_party_operations() {
  $operations = array(
    'merge' => array(
      'label' => t('Merge Parties'),
      'callback' => 'crm_party_party_operations_merge',
    ),
  );
  return $operations;
}

/**
 * Merge multiple users.
 */
function crm_party_party_operations_merge($parties) {

}
