<?php

/**
 * @file
 * Support for linking users to parties
 */

/**
 * Implements hook_crm_party_data_set_info()
 */
function crm_user_crm_party_data_set_info() {
  $sets['user'] = array(
    'label' => t("User account"),
    'entity type' => 'user',
    'class' => 'UserCRMController',
    'singleton' => TRUE,
    'max cardinality' => 1,
    'admin' => array(
      'edit' => 'admin/config/people/accounts',
      'manage fields' => 'admin/config/people/accounts/fields',
      'manage display' => 'admin/config/people/accounts/display',
    ),
    'form callback' => "crm_user_form_user",
  );
  return $sets;
}

/**
 * Implements hook_crm_party_party_pieces().
 */
function crm_user_crm_party_party_pieces() {
  return array(
    'user' => array(
      'title' => 'User',
      'page callback' => 'crm_party_view_data_set',
      'page arguments' => array(1, 'user'),
      'file' => 'crm_party.pages.inc', 
      'access callback' => TRUE,
      'access arguments' => array(1),
      'weight' => -8,
    ),
  );
}

/**
 * Menu access callback for the party user piece.
 */
function crm_user_party_view_user_access($party) {
  // @todo:
  // - check user_access() for viewing user accounts
  // - check there actually is a user account to show
  // @todo:
  // nice touch, maybe: if there is no user account to show, instead offer a 
  // form to connect one?
  return TRUE;
}

/**
 * Page callback for user party piece.
 */
function crm_user_party_view_user($party) {
  // @todo: display the user here.
  return 'The user is shown here.';
}

/**
 * Build the User Data Set form.
 */
function crm_user_form_user($form, &$form_state, &$attached_entity, $party) {
  $user_form = array();
  
  // If the user is set we load the edit account form.
  if ($attached_entity->eid !== NULL) {
    module_load_include('inc', 'user', 'user.pages');
    $user_form['op'] = array(
      '#type' => 'value',
      '#value' => 'edit',
    );
    
    $user_form = user_profile_form($user_form, $form_state, $attached_entity->entity);
    unset($user_form['actions']);
    
    // $form['#submit'][] = 'crm_user_user_edit_form_submit'; need to not exist
  }
  else {
    // Mark down that we're selecting which user to connect.
    $user_form['op'] = array(
      '#type' => 'value',
      '#value' => 'select',
    );
  
    // Store the account uid so we can check if it changes on submit.
    $user_form['crm_user_uid'] = array(
      '#type' => 'value',
      '#value' => isset($attached_entity->entity->uid) ? $attached_entity->entity->uid : NULL,
    );

    $user_form['user'] = array(
      '#type' => 'textfield',
      '#title' => t('User'),
      '#maxlength' => 60,
      '#autocomplete_path' => 'user/autocomplete',
      '#default_value' => isset($attached_entity->entity->name) ? $attached_entity->entity->name : '',
      '#weight' => -1,
      '#description' => t('Leave blank for %anonymous.', array('%anonymous' => variable_get('anonymous', t('Anonymous')))),
    );
    
    // $form['#submit'][] = 'crm_user_user_add_form_submit'; can't rely on this
  }
  
  return $user_form;
}

/**
 * Validate the user data set form
 *
 * @todo: Implement
 */
function crm_user_form_user_validate($form, &$form_state, &$attached_entity, $party) {
  return TRUE;
}

/**
 * Submit the user data set form
 */
function crm_user_form_user_submit($form, &$form_state, &$attached_entity, $party) {
  $hash = $attached_entity->hash();
  
  $op = $form_state['values'][$hash]['op'];
  
  if ($op == 'select') {
    // Attempt to load a user from the given input.
    $account = user_load_by_name($form_state['values'][$hash]['user']);
    $attached_entity->setAttachedEntity($account);
  }
  else if ($op == 'edit') {
    $account = $attached_entity->entity;
    $category = $form[$hash]['#user_category'];
    
    $edit = array_intersect_key((array) $account, $form_state['values'][$hash]);
    user_save($account, $edit, $category);
    
    if ($category == 'account' && !empty($edit['pass'])) {
      // Remove the password reset tag since a new password was saved.
      unset($_SESSION['pass_reset_' . $account->uid]);
    }
    cache_clear_all();
  }
}

/**
 * Controller class for CRM integration.
 *
 * @todo: move this to an inc file for autoloading.
 */
class UserCRMController extends EntityDefaultCRMController {
  const ENTITY_ID_KEY = "uid";
  
  // @todo remove
  const VIEW_MODE = "full";

  /**
   * Display a user dataSet
   *  This is needed because user doesn't use the entity API
   */
  public function display($mode) {
    return user_view($this->entity, $mode);
  }
  
  /**
   * Get the entity label
   */
  public function getLabel() {
    return format_username($this->entity);
  }
}

