<?php
/**
 * @file
 * Provides default classes for UI actions on data sets.
 */

/**
 * The 'add' action: attach a new entity.
 */
class PartyDefaultDataSetUIAdd {

  function action_form() {

  }

  function action_form_validate() {

  }

  function action_form_submit() {

  }

}

/**
 * The 'attach' action: attach an existing entity.
 */
class PartyDefaultDataSetUIAttach {

  function action_form() {

  }

  function action_form_validate() {

  }

  function action_form_submit() {

  }

}


